# Generated by Django 4.1.4 on 2023-05-24 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_calendar', '0004_label_cost_training_is_completed_payment'),
        ('users', '0005_trainingcount_profile_training_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='training_counts',
        ),
        migrations.RemoveField(
            model_name='trainingcount',
            name='profile',
        ),
        migrations.AddField(
            model_name='trainingcount',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='training_counts',
            field=models.ManyToManyField(related_name='trainigs_as_coach', through='users.TrainingCount', to='training_calendar.label', verbose_name='Количество тренировок'),
        ),
    ]
