# Generated by Django 4.1.4 on 2023-05-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_calendar', '0004_label_cost_training_is_completed_payment'),
        ('users', '0006_remove_profile_training_counts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_counts',
            field=models.ManyToManyField(related_name='trainigs_counts', through='users.TrainingCount', to='training_calendar.label', verbose_name='Количество тренировок'),
        ),
    ]
