# Generated by Django 4.1.4 on 2023-06-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_calendar', '0004_label_cost_training_is_completed_payment'),
        ('users', '0007_alter_user_training_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_counts',
            field=models.ManyToManyField(related_name='users_have_trains', through='users.TrainingCount', to='training_calendar.label', verbose_name='Количество тренировок'),
        ),
    ]
