# Generated by Django 4.1.4 on 2023-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название метки')),
                ('color', models.TextField(verbose_name='Цвет текста для элемента события')),
                ('backgroundColor', models.TextField(verbose_name='Цвет фона для элемента события')),
                ('dragBackgroundColor', models.TextField(verbose_name='Цвет фона при перетаскивании элемента события')),
                ('borderColor', models.TextField(verbose_name='Цвет левой границы элемента события')),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
    ]
