# Generated by Django 4.1.4 on 2023-02-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_calendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало тренировки')),
                ('end', models.DateTimeField(verbose_name='Конец тренировки')),
                ('client', models.ManyToManyField(null=True, related_name='trainigs_as_client', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
                ('coach', models.ManyToManyField(null=True, related_name='trainigs_as_coach', to=settings.AUTH_USER_MODEL, verbose_name='тренер')),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainigs', to='training_calendar.label', verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренеровки',
                'ordering': ('-id',),
            },
        ),
    ]
