# Generated by Django 4.1.4 on 2023-02-27 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_calendar', '0002_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='coach',
        ),
        migrations.AddField(
            model_name='training',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainigs_as_coach', to=settings.AUTH_USER_MODEL, verbose_name='тренер'),
        ),
    ]
