# Generated by Django 4.1.4 on 2023-05-24 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_calendar', '0003_remove_training_coach_training_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость тренировки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершена тренировка'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма оплаты')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_method', models.CharField(choices=[('наличные', 'наличные'), ('карта', 'карта'), ('ссылка', 'ссылка'), ('перевод', 'перевод')], max_length=255, verbose_name='Способ оплаты')),
                ('training_label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_calendar.label', verbose_name='Вид тренировки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплата тренировки',
                'verbose_name_plural': 'Оплаты тренировок',
            },
        ),
    ]
