# Generated by Django 4.1.4 on 2023-01-17 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='пометка')),
                ('signal_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата напоминания')),
                ('relevance', models.BooleanField(default=False, verbose_name='актуальность')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ('-id',),
            },
        ),
    ]
